# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

float32_csr_gaussian_kernels_cpp <- function(A, B, sigmas, percentile, scaling_factor, lower_limit, upper_quantile, truncate_low_distance = TRUE, symmetric = FALSE, normalization = 0L) {
    .Call(`_CoPro_float32_csr_gaussian_kernels_cpp`, A, B, sigmas, percentile, scaling_factor, lower_limit, upper_quantile, truncate_low_distance, symmetric, normalization)
}

float32_csr_xky_cpp <- function(p, j, x, dims, x_left, x_right, n_threads = 1L, symmetric = FALSE) {
    .Call(`_CoPro_float32_csr_xky_cpp`, p, j, x, dims, x_left, x_right, n_threads, symmetric)
}

float32_csr_matmul_cpp <- function(p, j, x, dims, input, n_threads = 1L, transpose = FALSE, symmetric = FALSE) {
    .Call(`_CoPro_float32_csr_matmul_cpp`, p, j, x, dims, input, n_threads, transpose, symmetric)
}

float32_csr_sums_cpp <- function(p, j, x, dims, symmetric = FALSE) {
    .Call(`_CoPro_float32_csr_sums_cpp`, p, j, x, dims, symmetric)
}

float32_csr_values_cpp <- function(x) {
    .Call(`_CoPro_float32_csr_values_cpp`, x)
}

frnn_grid_cpp <- function(A, B_sexp, radius) {
    .Call(`_CoPro_frnn_grid_cpp`, A, B_sexp, radius)
}
