# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

frnn_grid_cpp <- function(A, B_sexp, radius) {
    .Call(`_CoPro_frnn_grid_cpp`, A, B_sexp, radius)
}
